### ISSUE TITLE
Update battery max capacity and time.

### ISSUE THREAD

**Issue by marecek89** [Dominik-Workshop/Electronic_load#1]
How and where in the program should the increase in the maximum capacity of the measured battery be adjusted ? for example, I want to test a battery of 15000 mah and maybe higher than 100,000mah. What happens to the time when it reaches 99 hours? Thanks

**Comment by Dominik-Workshop** [comment]
In `battery.cpp`, line 26 there is `dtostrf(capacity, 5, 0, displayValue);`. The 5 represents the maximum amount of digits for the capacity measurements, so to measure capacities higher than 99.999mAh you have to change it to 6.
When it comes to the timer, I suppose it just overflows to 00:00:00 (not tested), but I guess 99h should be enough to complete the measurement.
Let me know if you need further clarification or assistance with the adjustments.
I'm sorry for my late reply.

**Comment by marecek89** [comment]
In mode_screen.hh line 84 it is not necessary to add ``0'' to the display ? I'm looking forward to when the program is ready. Will it be necessary to upload a program to the tester so that it works with a PC?

**Comment by Dominik-Workshop** [comment]
Line 84 in `mode_screen.hh` is just a comment to help when coding, so it doesn't matter, if that's what you mean.
The desktop app is now ready to use for windows, I just need to merge it to `master` and provide some installation and usage instructions (I'm just low on time recently). But you can test it already by going to branch `remote_app` and cloning/dowloading the repository. 
Yes, you have to upload the new code to the Electronic Load for it to work with the PC program.
To open the PC app you just have to open `desktop_app/release/windows-64bit/electronic_load_app.exe`. There is no installation required.
If you decide to check it out, please let me know if it works!

**Comment by marecek89** [comment]
I tested the initial version of the app. The app works fine. when displaying the graph and line, the highest value is displayed at the very top. it could be adjusted so that the scale moves a little more so that the top line is not parallel to the top ?

**Comment by Dominik-Workshop** [comment]
Thank you for testing it; it's nice to hear that it works.
You can uncheck the Plot from zero option in the settings to achieve the following result:
![plot_not_zero](https://github.com/Dominik-Workshop/Electronic_load/assets/100617381/5b1155ad-81de-49e9-ab4d-b5360378ae63)
Is this what you wanted to achieve?
The scale can't be moved arbitrarily, at least for now.

**Comment by marecek89** [comment]
the current scale obviously changes with the addition of current. in your example, the blue line is, for example, at the value 4 and it is high.. if, for example, the graph was at a value of 4A, the scale would be 1A more so that it would be clearer and more visible. I don't know if you understood me

**Comment by Dominik-Workshop** [comment]
Oh, ok, I think I understand now. I might consider this in future updates.
