### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by yo8ssv** [Dominik-Workshop/Electronic_load#4]
Hi,

Can you describe procedure for calibration? I'm trying to do but with out succes. I enabled memu 6 for calibration and when I compile it say that is greater than flash size. How it can be done, please.

Thank you

**Comment by Dominik-Workshop** [comment]
Hello.

Seems like the recently added feature took up the remaninig space. You can easily solve this issue by commenting other functions in main.cpp, for example batteryMeasurement() and transient(). This should provide enough space in uC's memory. When you are done with calibration, you can uncomment these functions and comment calibration().

Hope it helps.

**Comment by yo8ssv** [comment]
Ok, and how to save at the end of calibration procedure? It ask for yes or no, which button is yes and no?

**Comment by Dominik-Workshop** [comment]
Yes - Enter
No - Delete.
(It should be written on the LCD)

**Comment by Dominik-Workshop** [comment]
Posted [calibration guide](https://youtu.be/jx0t7Ovq4uw?si=9ajka1ZFl43V9Rm9) on YouTube.
